#!/bin/bash

if [ -z "$1" ]
then
  echo "Usage: vpn <profile> <action> <args>"
  exit 1
fi

if [ "$1" = "ls" ]
then
  echo "=================="
  echo "Available Profiles"
  echo "=================="
  openvpn3 configs-list
  echo
  echo "================"
  echo "Current Sessions"
  echo "================"
  openvpn3 sessions-list
  exit 0
fi

PROFILE_NAME=$1

case $2 in
  start)
    if [ -z "$3" ]
    then
      read -p "Enter MFA: " MFA
    else
      MFA=$3
    fi
    USERNAME=$(secret-tool lookup service $PROFILE_NAME credentials username)
    PASSWORD=$(secret-tool lookup service $PROFILE_NAME credentials password)
    cat <<EOF | openvpn3 session-start --config $PROFILE_NAME > /dev/null 2>&1
$USERNAME
$PASSWORD
$MFA
EOF
    if [ $? -eq "0" ]
    then
      echo "$PROFILE_NAME VPN session started"
    else
      echo "Failed to connect"
      exit 1
    fi
    ;;
  stop)
    openvpn3 session-manage --disconnect --config $PROFILE_NAME
    ;;
  set)
    if [[ (-z "$3") || ("$3" != "username" && "$3" != "password") ]] 
    then
      echo "Attribute required: username, password"
      exit 1
    fi
    ATTRIBUTE=$3
    if [ "$ATTRIBUTE" = "username" ]
    then
      if [ -z "$4" ]
      then
        read -p "Enter username: " VALUE
      else
        VALUE=$4
      fi
    elif [ "$ATTRIBUTE" = "password" ]
    then
      read -s -p "Enter password: " VALUE
      echo
    fi
    echo -n $VALUE | secret-tool store --label='OpenVPN' service $PROFILE_NAME credentials $ATTRIBUTE
    echo "Set/updated $ATTRIBUTE for profile $PROFILE_NAME"
    ;;
  import)
    if [ -z "$3" ]
    then
      echo "Filename needed, e.g. \"vpn someprofile import ./client.ovpn\""
      exit 1
    fi
    FILENAME=$3
    openvpn3 config-import --config $3 --name $PROFILE_NAME --persistent 
    ;;
  remove)
    openvpn3 config-remove --config $PROFILE_NAME
    ;;
  *)
    echo "Action required: <profile> start, stop, set (username|password), import {filename}"
    exit 1
    ;;
esac
